/**
 * Give Me Doc — Lucide Icon SVG strings (auto-generated)
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: scripts/build_icons.py
 *
 * All icons share a common SVG attribute set via the S constant.
 * Each export is a complete <svg> string ready for innerHTML injection.
 */

const S = 'xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

/** file-text — document export */
export const ICON_FILE_TEXT = `<svg ${S}><path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/> <path d="M14 2v5a1 1 0 0 0 1 1h5"/> <path d="M10 9H8"/> <path d="M16 13H8"/> <path d="M16 17H8"/></svg>`;

/** file-type — file type badge (single message export) */
export const ICON_FILE_TYPE = `<svg ${S}><path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/> <path d="M14 2v5a1 1 0 0 0 1 1h5"/> <path d="M11 18h2"/> <path d="M12 12v6"/> <path d="M9 13v-.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5v.5"/></svg>`;

/** download — download / export */
export const ICON_DOWNLOAD = `<svg ${S}><path d="M12 15V3"/> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/> <path d="m7 10 5 5 5-5"/></svg>`;

/** upload — upload template */
export const ICON_UPLOAD = `<svg ${S}><path d="M12 3v12"/> <path d="m17 8-5-5-5 5"/> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/></svg>`;

/** trash-2 — delete */
export const ICON_TRASH = `<svg ${S}><path d="M10 11v6"/> <path d="M14 11v6"/> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/> <path d="M3 6h18"/> <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>`;

/** chevron-left — previous branch */
export const ICON_CHEVRON_LEFT = `<svg ${S}><path d="m15 18-6-6 6-6"/></svg>`;

/** chevron-right — next branch */
export const ICON_CHEVRON_RIGHT = `<svg ${S}><path d="m9 18 6-6-6-6"/></svg>`;

/** chevron-down — dropdown indicator */
export const ICON_CHEVRON_DOWN = `<svg ${S}><path d="m6 9 6 6 6-6"/></svg>`;

/** check — checkmark / confirm */
export const ICON_CHECK = `<svg ${S}><path d="M20 6 9 17l-5-5"/></svg>`;

/** x — close / dismiss */
export const ICON_X = `<svg ${S}><path d="M18 6 6 18"/> <path d="m6 6 12 12"/></svg>`;

/** settings — settings tab */
export const ICON_SETTINGS = `<svg ${S}><path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/> <circle cx="12" cy="12" r="3"/></svg>`;

/** info — about tab / info toast */
export const ICON_INFO = `<svg ${S}><circle cx="12" cy="12" r="10"/> <path d="M12 16v-4"/> <path d="M12 8h.01"/></svg>`;

/** external-link — open in new tab */
export const ICON_EXTERNAL_LINK = `<svg ${S}><path d="M15 3h6v6"/> <path d="M10 14 21 3"/> <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>`;

/** list — export tab list */
export const ICON_LIST = `<svg ${S}><path d="M3 5h.01"/> <path d="M3 12h.01"/> <path d="M3 19h.01"/> <path d="M8 5h13"/> <path d="M8 12h13"/> <path d="M8 19h13"/></svg>`;

/** star — set as default */
export const ICON_STAR = `<svg ${S}><path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/></svg>`;

/** refresh-cw — refresh session */
export const ICON_REFRESH = `<svg ${S}><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/> <path d="M21 3v5h-5"/> <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/> <path d="M8 16H3v5"/></svg>`;

/** github — GitHub link */
export const ICON_GITHUB = `<svg ${S}><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/> <path d="M9 18c-4.51 2-5-2-7-2"/></svg>`;

/** bug — report issue */
export const ICON_BUG = `<svg ${S}><path d="M12 20v-9"/> <path d="M14 7a4 4 0 0 1 4 4v3a6 6 0 0 1-12 0v-3a4 4 0 0 1 4-4z"/> <path d="M14.12 3.88 16 2"/> <path d="M21 21a4 4 0 0 0-3.81-4"/> <path d="M21 5a4 4 0 0 1-3.55 3.97"/> <path d="M22 13h-4"/> <path d="M3 21a4 4 0 0 1 3.81-4"/> <path d="M3 5a4 4 0 0 0 3.55 3.97"/> <path d="M6 13H2"/> <path d="m8 2 1.88 1.88"/> <path d="M9 7.13V6a3 3 0 1 1 6 0v1.13"/></svg>`;

/** user — user message */
export const ICON_USER = `<svg ${S}><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/> <circle cx="12" cy="7" r="4"/></svg>`;

/** bot — assistant message */
export const ICON_BOT = `<svg ${S}><path d="M12 8V4H8"/> <rect width="16" height="12" x="4" y="8" rx="2"/> <path d="M2 14h2"/> <path d="M20 14h2"/> <path d="M15 13v2"/> <path d="M9 13v2"/></svg>`;

/** circle-check — success toast */
export const ICON_CIRCLE_CHECK = `<svg ${S}><circle cx="12" cy="12" r="10"/> <path d="m9 12 2 2 4-4"/></svg>`;

/** triangle-alert — warning toast */
export const ICON_TRIANGLE_ALERT = `<svg ${S}><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/> <path d="M12 9v4"/> <path d="M12 17h.01"/></svg>`;

/** circle-x — error toast */
export const ICON_CIRCLE_X = `<svg ${S}><circle cx="12" cy="12" r="10"/> <path d="m15 9-6 6"/> <path d="m9 9 6 6"/></svg>`;

// ── Size helper ────────────────────────────────────────────────────────

/**
 * Create a size variant of an icon SVG string.
 * Replaces width="20" height="20" with the given size.
 */
export function iconSize(svg: string, size: number): string {
  return svg
    .replace('width="20"', `width="${size}"`)
    .replace('height="20"', `height="${size}"`);
}

/**
 * Create an icon SVG with custom stroke-width.
 * Useful for checkbox/switch marks that need thicker strokes.
 */
export function iconStroke(svg: string, strokeWidth: number): string {
  return svg.replace('stroke-width="2"', `stroke-width="${strokeWidth}"`);
}

