#!/usr/bin/env python3
"""
build_templates.py — 根据 config.yaml 生成内置 Word 模板

读取 templates/config.yaml 中的样式定义，基于 pandoc 默认 reference.docx
修改字体/字号/行距等样式，输出:
    1. templates/<id>.docx               — 可作为 pandoc reference-doc 使用
    2. src/core/builtin-templates.generated.ts — base64 嵌入，运行时种子数据

用法:
    python3 scripts/build_templates.py           # 从项目根目录运行
    pnpm build:templates                         # 等效 npm script

依赖:
    pip install python-docx pyyaml
"""
from __future__ import annotations

import base64
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not found. Please install it with `pip install pyyaml`.", file=sys.stderr)
    sys.exit(1)

# Pre-committed base reference.docx (generated by pandoc --print-default-data-file reference.docx)
# Using this avoids requiring pandoc CLI at build time.
PRECOMMITTED_BASE_DOCX = Path(__file__).resolve().parent.parent / "templates" / "pandoc-reference-base.docx"

# Verify python-docx can be imported and is functional
try:
    from docx import Document
    from docx.shared import Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
    from docx.enum.style import WD_STYLE_TYPE
    from docx.oxml.ns import qn
except ImportError:
    print("ERROR: python-docx not found. Please install it with `pip install python-docx`.", file=sys.stderr)
    sys.exit(1)

# Styles that should be created as CHARACTER type when missing
_CHAR_STYLES = {"Verbatim Char", "Body Text Char", "Footnote Reference",
                "Hyperlink", "Section Number", "Default Paragraph Font"}

# Styles that should be treated as TABLE type
_TABLE_STYLES = {"Table"}

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
TEMPLATES_DIR = ROOT_DIR / "templates"
CONFIG_PATH = TEMPLATES_DIR / "config.yaml"
OUTPUT_TS_PATH = ROOT_DIR / "src" / "core" / "builtin-templates.generated.ts"

ALIGNMENT_MAP = {
    "left": WD_ALIGN_PARAGRAPH.LEFT,
    "center": WD_ALIGN_PARAGRAPH.CENTER,
    "right": WD_ALIGN_PARAGRAPH.RIGHT,
    "justify": WD_ALIGN_PARAGRAPH.JUSTIFY,
}


def load_config() -> dict[str, Any]:
    """Load and validate config.yaml, resolving external styles_file references."""
    if not CONFIG_PATH.exists():
        print(f"ERROR: config not found: {CONFIG_PATH}", file=sys.stderr)
        sys.exit(1)
    with open(CONFIG_PATH, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if "templates" not in cfg or not cfg["templates"]:
        print("ERROR: config.yaml must define at least one template", file=sys.stderr)
        sys.exit(1)

    # Resolve external style files: if a template has styles_file instead of
    # inline styles, load the referenced YAML and merge into the template dict.
    for tpl in cfg["templates"]:
        styles_file = tpl.pop("styles_file", None)
        if styles_file and "styles" not in tpl:
            styles_path = TEMPLATES_DIR / styles_file
            if not styles_path.exists():
                print(f"ERROR: styles file not found: {styles_path}", file=sys.stderr)
                sys.exit(1)
            with open(styles_path, encoding="utf-8") as f:
                styles = yaml.safe_load(f)
            if not isinstance(styles, dict):
                print(f"ERROR: styles file must be a YAML mapping: {styles_path}", file=sys.stderr)
                sys.exit(1)
            tpl["styles"] = styles

    return cfg


def generate_base_reference_doc(output_path: Path) -> None:
    """Get the default reference.docx — prefer pre-committed file, fallback to pandoc CLI."""
    if PRECOMMITTED_BASE_DOCX.exists():
        shutil.copy2(PRECOMMITTED_BASE_DOCX, output_path)
        return
    # Fallback: generate from pandoc CLI
    pandoc = shutil.which("pandoc")
    if not pandoc:
        print("ERROR: pandoc-reference-base.docx not found and pandoc not in PATH.", file=sys.stderr)
        print("  Either commit templates/pandoc-reference-base.docx or install pandoc.", file=sys.stderr)
        sys.exit(1)
    subprocess.run(
        [pandoc, "--print-default-data-file", "reference.docx"],
        stdout=open(output_path, "wb"),
        check=True,
    )


def set_run_font(run_or_rpr, *, ascii: str | None, east_asia: str | None) -> None:
    """Set font names on a run or rPr element using OOXML.

    Importantly, this also removes any theme font attributes (asciiTheme,
    hAnsiTheme, eastAsiaTheme, cstheme) that would otherwise override the
    explicit font names we set.  Pandoc's default reference.docx uses theme
    fonts on Heading styles, which is why headings revert to Calibri + 宋体
    unless the theme attributes are stripped.
    """
    # Find or create rFonts element
    rpr = run_or_rpr
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = rpr.makeelement(qn("w:rFonts"), {})
        rpr.insert(0, rfonts)
    if ascii:
        rfonts.set(qn("w:ascii"), ascii)
        rfonts.set(qn("w:hAnsi"), ascii)
        # Remove theme overrides so explicit names take effect
        for attr in (qn("w:asciiTheme"), qn("w:hAnsiTheme")):
            rfonts.attrib.pop(attr, None)
    if east_asia:
        rfonts.set(qn("w:eastAsia"), east_asia)
        rfonts.attrib.pop(qn("w:eastAsiaTheme"), None)
    # Also clear cstheme if we're setting any explicit font
    if ascii or east_asia:
        rfonts.attrib.pop(qn("w:cstheme"), None)


# ---------------------------------------------------------------------------
# Table style helpers
# ---------------------------------------------------------------------------

# Valid border style values for OOXML w:val attribute
_BORDER_VALS = {"none", "single", "double", "dotted", "dashed", "thick",
                "dashSmallGap", "dotDash", "dotDotDash", "triple",
                "thinThickSmallGap", "thickThinSmallGap",
                "thinThickMediumGap", "thickThinMediumGap",
                "thinThickLargeGap", "thickThinLargeGap", "wave",
                "doubleWave", "dashDotStroked", "threeDEmboss",
                "threeDEngrave", "outset", "inset", "nil"}

# Conditional formatting area types supported by OOXML
_COND_TYPES = {"firstRow", "lastRow", "firstCol", "lastCol",
               "band1Horz", "band2Horz", "band1Vert", "band2Vert",
               "neCell", "nwCell", "seCell", "swCell"}

ALIGNMENT_JC_MAP = {
    "left": "start",
    "center": "center",
    "right": "end",
    "justify": "both",
}


def _make_border_el(parent, tag: str, cfg: dict[str, Any]) -> None:
    """Create a single border element (e.g. <w:top>) under *parent*.

    cfg keys: val (str), sz (int, half-pt, 4=0.5pt), color (hex str), space (int, default 0)
    """
    val = str(cfg.get("val", "single"))
    attrs = {qn("w:val"): val}
    if val not in ("none", "nil"):
        attrs[qn("w:sz")] = str(cfg.get("sz", 4))
        attrs[qn("w:color")] = cfg.get("color", "auto")
        attrs[qn("w:space")] = str(cfg.get("space", 0))
    el = parent.makeelement(qn(f"w:{tag}"), attrs)
    parent.append(el)


def _make_borders(parent, borders_cfg: dict[str, Any], tag: str = "tblBorders") -> None:
    """Build a <w:tblBorders> or <w:tcBorders> element under *parent*."""
    borders_el = parent.makeelement(qn(f"w:{tag}"), {})
    # Order matters in OOXML schema: top, left, bottom, right, insideH, insideV
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        if side in borders_cfg:
            _make_border_el(borders_el, side, borders_cfg[side])
    parent.append(borders_el)


def _make_shd(parent, fill: str) -> None:
    """Create a <w:shd> element (works in rPr for char shading, tcPr for cell shading)."""
    shd = parent.makeelement(qn("w:shd"), {
        qn("w:val"): "clear",
        qn("w:color"): "auto",
        qn("w:fill"): fill,
    })
    parent.append(shd)


def _make_spacing(parent, *, line_spacing=None, line_spacing_pt=None, space_before_pt=None, space_after_pt=None) -> None:
    """Create a <w:spacing> element under a <w:pPr> for paragraph spacing.

    line_spacing: multiplier (e.g. 1.5 = 1.5x); maps to lineRule="auto"
    line_spacing_pt: fixed/exact line spacing in points; maps to lineRule="exact"
    If both are given, line_spacing_pt takes precedence.
    """
    attrs = {}
    if line_spacing_pt is not None:
        # Exact (fixed) line spacing: OOXML uses twips (1 pt = 20 twips)
        attrs[qn("w:line")] = str(int(line_spacing_pt * 20))
        attrs[qn("w:lineRule")] = "exact"
    elif line_spacing is not None:
        # Multiple line spacing: OOXML uses 240ths of a line
        attrs[qn("w:line")] = str(int(line_spacing * 240))
        attrs[qn("w:lineRule")] = "auto"
    if space_before_pt is not None:
        # OOXML uses twips (1 pt = 20 twips)
        attrs[qn("w:before")] = str(int(space_before_pt * 20))
    if space_after_pt is not None:
        attrs[qn("w:after")] = str(int(space_after_pt * 20))
    if attrs:
        spacing = parent.makeelement(qn("w:spacing"), attrs)
        parent.append(spacing)


def _build_cond_rpr(parent, cond_cfg: dict[str, Any]) -> None:
    """Build <w:rPr> inside a <w:tblStylePr> from conditional config."""
    has_font = cond_cfg.get("font_ascii") or cond_cfg.get("font_eastAsia")
    has_bold = "bold" in cond_cfg
    has_italic = "italic" in cond_cfg
    has_color = "color" in cond_cfg
    has_size = "font_size_pt" in cond_cfg
    has_char_shading = "char_shading" in cond_cfg

    if not (has_font or has_bold or has_italic or has_color or has_size or has_char_shading):
        return

    rpr = parent.makeelement(qn("w:rPr"), {})
    if has_font:
        set_run_font(rpr, ascii=cond_cfg.get("font_ascii"), east_asia=cond_cfg.get("font_eastAsia"))
    if has_bold:
        b_el = rpr.makeelement(qn("w:b"), {qn("w:val"): "1" if cond_cfg["bold"] else "0"})
        rpr.append(b_el)
    if has_italic:
        i_el = rpr.makeelement(qn("w:i"), {qn("w:val"): "1" if cond_cfg["italic"] else "0"})
        rpr.append(i_el)
    if has_color:
        c_el = rpr.makeelement(qn("w:color"), {qn("w:val"): cond_cfg["color"]})
        rpr.append(c_el)
    if has_size:
        # w:sz is in half-points
        sz_el = rpr.makeelement(qn("w:sz"), {qn("w:val"): str(int(cond_cfg["font_size_pt"] * 2))})
        rpr.append(sz_el)
        szCs = rpr.makeelement(qn("w:szCs"), {qn("w:val"): str(int(cond_cfg["font_size_pt"] * 2))})
        rpr.append(szCs)
    if has_char_shading:
        _make_shd(rpr, cond_cfg["char_shading"])
    parent.append(rpr)


def _build_cond_ppr(parent, cond_cfg: dict[str, Any]) -> None:
    """Build <w:pPr> inside a <w:tblStylePr> from conditional config."""
    has_align = "alignment" in cond_cfg
    has_spacing = any(k in cond_cfg for k in ("line_spacing", "line_spacing_pt", "space_before_pt", "space_after_pt"))

    if not (has_align or has_spacing):
        return

    ppr = parent.makeelement(qn("w:pPr"), {})
    if has_align:
        jc_val = ALIGNMENT_JC_MAP.get(cond_cfg["alignment"])
        if jc_val:
            jc = ppr.makeelement(qn("w:jc"), {qn("w:val"): jc_val})
            ppr.append(jc)
    if has_spacing:
        _make_spacing(ppr,
                      line_spacing=cond_cfg.get("line_spacing"),
                      line_spacing_pt=cond_cfg.get("line_spacing_pt"),
                      space_before_pt=cond_cfg.get("space_before_pt"),
                      space_after_pt=cond_cfg.get("space_after_pt"))
    parent.append(ppr)


def _build_cond_tcpr(parent, cond_cfg: dict[str, Any]) -> None:
    """Build <w:tcPr> inside a <w:tblStylePr> from conditional config."""
    has_borders = "borders" in cond_cfg
    has_shading = "shading" in cond_cfg
    has_valign = "vertical_alignment" in cond_cfg

    if not (has_borders or has_shading or has_valign):
        return

    tcpr = parent.makeelement(qn("w:tcPr"), {})
    if has_borders:
        _make_borders(tcpr, cond_cfg["borders"], tag="tcBorders")
    if has_shading:
        _make_shd(tcpr, cond_cfg["shading"])
    if has_valign:
        va_val = cond_cfg["vertical_alignment"]  # top, center, bottom
        va = tcpr.makeelement(qn("w:vAlign"), {qn("w:val"): va_val})
        tcpr.append(va)
    parent.append(tcpr)


def apply_table_style(doc: Document, style_name: str, props: dict[str, Any]) -> None:
    """Apply table style properties (borders, cell margins, conditional formatting).

    This operates on WD_STYLE_TYPE.TABLE styles using low-level OOXML because
    python-docx has very limited high-level API support for table styles.
    """
    # Find existing table style
    style = None
    for s in doc.styles:
        if s.name == style_name and s.type == WD_STYLE_TYPE.TABLE:
            style = s
            break

    if style is None:
        try:
            style = doc.styles.add_style(style_name, WD_STYLE_TYPE.TABLE)
            style.base_style = doc.styles["Table Normal"]
            print(f"    + created table style: '{style_name}'")
        except Exception as e:
            print(f"  WARNING: could not create table style '{style_name}': {e}")
            return

    style_el = style.element

    # --- Clear existing tblPr sub-elements we're about to set ---
    tbl_pr = style_el.find(qn("w:tblPr"))
    if tbl_pr is None:
        tbl_pr = style_el.makeelement(qn("w:tblPr"), {})
        style_el.append(tbl_pr)

    # Remove existing borders, cell margins, jc (we'll recreate them)
    for old_tag in ("w:tblBorders", "w:tblCellMar", "w:jc"):
        old = tbl_pr.find(qn(old_tag))
        if old is not None:
            tbl_pr.remove(old)

    # Remove ALL existing tblStylePr (conditional formatting sections)
    for old_cond in style_el.findall(qn("w:tblStylePr")):
        style_el.remove(old_cond)

    # Remove existing top-level rPr and pPr on the table style
    for old_tag in ("w:rPr", "w:pPr"):
        old = style_el.find(qn(old_tag))
        if old is not None:
            style_el.remove(old)

    # --- 0) Table alignment (horizontal position on page) ---
    table_alignment = props.get("table_alignment")
    if table_alignment:
        jc_val = ALIGNMENT_JC_MAP.get(table_alignment)
        if jc_val:
            jc = tbl_pr.makeelement(qn("w:jc"), {qn("w:val"): jc_val})
            tbl_pr.append(jc)

    # --- 1) Table borders ---
    borders_cfg = props.get("borders")
    if borders_cfg:
        _make_borders(tbl_pr, borders_cfg)

    # --- 2) Cell margins ---
    cell_margin_cfg = props.get("cell_margin")
    if cell_margin_cfg:
        cm_el = tbl_pr.makeelement(qn("w:tblCellMar"), {})
        for side in ("top", "left", "bottom", "right"):
            if side in cell_margin_cfg:
                side_el = cm_el.makeelement(qn(f"w:{side}"), {
                    qn("w:w"): str(cell_margin_cfg[side]),
                    qn("w:type"): "dxa",
                })
                cm_el.append(side_el)
        tbl_pr.append(cm_el)

    # --- 3) Table-level default cell properties (shading, vertical alignment) ---
    has_shading = "shading" in props
    has_valign = "vertical_alignment" in props
    if has_shading or has_valign:
        # These are expressed as default tcPr on the table style
        tcpr = style_el.makeelement(qn("w:tcPr"), {})
        if has_shading:
            _make_shd(tcpr, props["shading"])
        if has_valign:
            va = tcpr.makeelement(qn("w:vAlign"), {qn("w:val"): props["vertical_alignment"]})
            tcpr.append(va)
        # Insert tcPr after tblPr per schema order
        tbl_pr_index = list(style_el).index(tbl_pr)
        style_el.insert(tbl_pr_index + 1, tcpr)

    # --- 4) Conditional formatting ---
    cond_cfg = props.get("conditional")
    if cond_cfg:
        for cond_type, cond_props in cond_cfg.items():
            if cond_type not in _COND_TYPES:
                print(f"  WARNING: unknown conditional type '{cond_type}', skipping")
                continue
            tsp = style_el.makeelement(qn("w:tblStylePr"), {qn("w:type"): cond_type})
            # Build in OOXML schema order: pPr, rPr, tblPr, trPr, tcPr
            _build_cond_ppr(tsp, cond_props)
            _build_cond_rpr(tsp, cond_props)
            _build_cond_tcpr(tsp, cond_props)
            style_el.append(tsp)

    print(f"    ✓ table style: '{style_name}'")


def _insert_rpr_after_metadata(style_el, rpr) -> None:
    """Insert rPr element after style metadata elements in correct schema order."""
    # Remove if already appended
    if rpr.getparent() is not None:
        rpr.getparent().remove(rpr)
    # Schema order: name, aliases, basedOn, next, link, autoRedefine, hidden,
    #               uiPriority, semiHidden, unhideWhenUsed, qFormat, locked,
    #               personal*, rsid, rPr, ...
    metadata_tags = {qn(f"w:{t}") for t in (
        "name", "aliases", "basedOn", "next", "link", "autoRedefine",
        "hidden", "uiPriority", "semiHidden", "unhideWhenUsed",
        "qFormat", "locked", "personal", "personalCompose",
        "personalReply", "rsid",
    )}
    insert_pos = 0
    for i, child in enumerate(style_el):
        if child.tag in metadata_tags:
            insert_pos = i + 1
        else:
            break
    style_el.insert(insert_pos, rpr)


def apply_style(doc: Document, style_name: str, props: dict[str, Any]) -> None:
    """Apply style properties to a named style in the document."""
    # Delegate table styles to specialized handler
    if style_name in _TABLE_STYLES or _is_table_style_props(props):
        apply_table_style(doc, style_name, props)
        return

    # Find the style object
    style = None
    for s in doc.styles:
        if s.name == style_name:
            style = s
            break

    if style is None:
        # Auto-create missing styles so pandoc picks them up
        try:
            if style_name in _CHAR_STYLES:
                style = doc.styles.add_style(style_name, WD_STYLE_TYPE.CHARACTER)
            else:
                style = doc.styles.add_style(style_name, WD_STYLE_TYPE.PARAGRAPH)
                style.base_style = doc.styles["Normal"]
            print(f"    + created style: '{style_name}'")
        except Exception as e:
            print(f"  WARNING: could not create style '{style_name}': {e}")
            return

    # Font settings
    font_ascii = props.get("font_ascii")
    font_east_asia = props.get("font_eastAsia")
    font_size = props.get("font_size_pt")
    bold = props.get("bold")
    color = props.get("color")

    if font_ascii or font_east_asia:
        # Use low-level API for full CJK font control
        rpr = style.element.find(qn("w:rPr"))
        if rpr is None:
            rpr = style.element.makeelement(qn("w:rPr"), {})
            style.element.append(rpr)
        set_run_font(rpr, ascii=font_ascii, east_asia=font_east_asia)

        # Also set via python-docx high-level API for ascii/hAnsi
        if font_ascii and hasattr(style, "font"):
            style.font.name = font_ascii

    if font_size is not None and hasattr(style, "font"):
        style.font.size = Pt(font_size)

    if bold is not None and hasattr(style, "font"):
        style.font.bold = bold

    italic = props.get("italic")
    if italic is not None and hasattr(style, "font"):
        style.font.italic = italic

    if color and hasattr(style, "font"):
        style.font.color.rgb = RGBColor.from_string(color)

    underline = props.get("underline")
    if underline is not None and hasattr(style, "font"):
        style.font.underline = underline

    # Character shading (text background color)
    char_shading = props.get("char_shading")
    if char_shading:
        rpr = style.element.find(qn("w:rPr"))
        if rpr is None:
            rpr = style.element.makeelement(qn("w:rPr"), {})
            style.element.append(rpr)
        # Remove existing shd if present
        old_shd = rpr.find(qn("w:shd"))
        if old_shd is not None:
            rpr.remove(old_shd)
        _make_shd(rpr, char_shading)

    # Paragraph settings
    if hasattr(style, "paragraph_format"):
        pf = style.paragraph_format
        if "line_spacing_pt" in props:
            # Fixed/exact line spacing in points
            pf.line_spacing = Pt(props["line_spacing_pt"])
            pf.line_spacing_rule = WD_LINE_SPACING.EXACTLY
        elif "line_spacing" in props:
            pf.line_spacing = props["line_spacing"]
        if "space_before_pt" in props:
            pf.space_before = Pt(props["space_before_pt"])
        if "space_after_pt" in props:
            pf.space_after = Pt(props["space_after_pt"])
        if "alignment" in props:
            align = props["alignment"]
            if align in ALIGNMENT_MAP:
                pf.alignment = ALIGNMENT_MAP[align]
        if "first_line_indent_pt" in props:
            pf.first_line_indent = Pt(props["first_line_indent_pt"])
        if "indent_left_pt" in props:
            pf.left_indent = Pt(props["indent_left_pt"])
        if "indent_right_pt" in props:
            pf.right_indent = Pt(props["indent_right_pt"])
        if "keep_with_next" in props:
            pf.keep_with_next = props["keep_with_next"]
        if "keep_together" in props:
            pf.keep_together = props["keep_together"]
        if "widow_control" in props:
            pf.widow_control = props["widow_control"]
        if "page_break_before" in props:
            pf.page_break_before = props["page_break_before"]


def _is_table_style_props(props: dict[str, Any]) -> bool:
    """Detect if props dict contains table-style-specific keys."""
    return any(k in props for k in ("borders", "cell_margin", "conditional", "table_alignment"))


def apply_page_setup(doc: Document, page_cfg: dict[str, Any]) -> None:
    """Apply page size and margins."""
    for section in doc.sections:
        if "width_cm" in page_cfg:
            section.page_width = Cm(page_cfg["width_cm"])
        if "height_cm" in page_cfg:
            section.page_height = Cm(page_cfg["height_cm"])
        if "margin_top_cm" in page_cfg:
            section.top_margin = Cm(page_cfg["margin_top_cm"])
        if "margin_bottom_cm" in page_cfg:
            section.bottom_margin = Cm(page_cfg["margin_bottom_cm"])
        if "margin_left_cm" in page_cfg:
            section.left_margin = Cm(page_cfg["margin_left_cm"])
        if "margin_right_cm" in page_cfg:
            section.right_margin = Cm(page_cfg["margin_right_cm"])


def build_template(
    base_docx_path: Path,
    tpl_cfg: dict[str, Any],
    global_defaults: dict[str, Any],
) -> Path:
    """Create a styled .docx template and return its output path."""
    tpl_id = tpl_cfg["id"]
    tpl_name = tpl_cfg["name"]
    output_path = TEMPLATES_DIR / f"{tpl_id}.docx"

    print(f"  Building: {tpl_id} ({tpl_name})")

    doc = Document(str(base_docx_path))

    # Apply global page setup
    page_cfg = global_defaults.get("page", {})
    apply_page_setup(doc, page_cfg)

    # Apply template-specific page setup (overrides global)
    tpl_page_cfg = tpl_cfg.get("page", {})
    if tpl_page_cfg:
        apply_page_setup(doc, tpl_page_cfg)

    # Apply global paragraph defaults to Normal style first
    para_defaults = global_defaults.get("paragraph", {})
    if para_defaults:
        apply_style(doc, "Normal", {
            "line_spacing": para_defaults.get("line_spacing"),
            "space_after_pt": para_defaults.get("space_after_pt"),
        })

    # Apply template-specific style overrides
    styles = tpl_cfg.get("styles", {})
    for style_name, style_props in styles.items():
        apply_style(doc, style_name, style_props)

    doc.save(str(output_path))
    print(f"    → {output_path.relative_to(ROOT_DIR)}")
    return output_path


def generate_ts_embed(template_paths: list[tuple[str, str, str, Path]]) -> None:
    """Generate builtin-templates.generated.ts with base64-encoded template data."""
    print(f"\n  Generating TypeScript embed: {OUTPUT_TS_PATH.relative_to(ROOT_DIR)}")

    lines = [
        "/**",
        " * Auto-generated by scripts/build_templates.py",
        " * DO NOT EDIT MANUALLY — run `pnpm build:templates` to regenerate.",
        " */",
        "",
        "export interface BuiltinTemplate {",
        "  name: string;",
        "  description: string;",
        "  data: string; // base64-encoded .docx",
        "}",
        "",
        "export const BUILTIN_TEMPLATES: Record<string, BuiltinTemplate> = {",
    ]

    for tpl_id, tpl_name, tpl_desc, docx_path in template_paths:
        with open(docx_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        # Split into 80-char lines for readability
        chunks = [b64[i : i + 80] for i in range(0, len(b64), 80)]
        joined = "' +\n    '".join(chunks)
        lines.append(f"  '{tpl_id}': {{")
        lines.append(f"    name: '{tpl_name}',")
        lines.append(f"    description: '{tpl_desc}',")
        lines.append(f"    data:")
        lines.append(f"    '{joined}',")
        lines.append(f"  }},")

    lines.append("};")
    lines.append("")

    OUTPUT_TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_TS_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # Report sizes
    for tpl_id, tpl_name, tpl_desc, docx_path in template_paths:
        size_kb = docx_path.stat().st_size / 1024
        print(f"    {tpl_id}: {size_kb:.1f} KB")


def main() -> None:
    print("=== Give Me Doc: Building Word templates ===\n")

    cfg = load_config()
    global_defaults = cfg.get("defaults", {})

    # Step 1: Generate pandoc default reference.docx as base
    with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
        base_path = Path(tmp.name)

    try:
        print("  Generating pandoc base reference.docx ...")
        generate_base_reference_doc(base_path)
        print(f"    → base: {base_path.stat().st_size / 1024:.1f} KB\n")

        # Step 2: Build each template
        template_paths: list[tuple[str, str, str, Path]] = []
        for tpl_cfg in cfg["templates"]:
            out = build_template(base_path, tpl_cfg, global_defaults)
            template_paths.append((
                tpl_cfg["id"],
                tpl_cfg["name"],
                tpl_cfg.get("description", ""),
                out,
            ))

        # Step 3: Generate TypeScript embed
        generate_ts_embed(template_paths)

    finally:
        base_path.unlink(missing_ok=True)

    print("\n=== Done! ===")


if __name__ == "__main__":
    main()
